apiVersion: v2
name: raw
description: "Render raw kubernetes manifests managed by a helm release"
type: application
version: 1.0.0
appVersion: 1.0.12
icon: "https://www.bedag.ch/wGlobal/wGlobal/layout/images/logo.svg"
home: "https://github.com/bedag/helm-charts/tree/master/charts/raw"
keywords:
  - raw
  - templates
  - resources
maintainers:
  - name: SRE
    email: sre@bedag.ch
dependencies:
  - name: "library"
    version: "~0.3.0"
    repository: "https://buttahtoast.github.io/helm-charts/"    
sources:
  - https://github.com/bedag/helm-charts/tree/master/charts/raw
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - "[Added]: Chart Initialization"
  artifacthub.io/prerelease: "false"
