apiVersion: v2
name: common
description: "Bedag's common Helm chart to use for creating other Helm charts"
version: 10.3.0
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.

# Because linting (in helm-v3.0.0) doesnt work correctly we use type application
type: application
icon: "https://www.bedag.ch/wGlobal/wGlobal/layout/images/logo.svg"
keywords:
- Bedag
- Common
sources:
- https://github.com/bedag/helm-charts/tree/master/charts/common
maintainers:
  - name: SRE
    email: sre@bedag.ch
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - "[Added]: support for clusterIP field"
