{{- if (include "kubernetes.enabled" $) -}}
  {{- $kubernetes := $.Values.kubernetes -}}
  {{- if $kubernetes.apiServer.enabled -}}
    {{- $fullName := include "kubernetes.fullname" . -}}
    {{- $component_name := "apiserver" -}}
    {{- if $kubernetes.apiServer.podDisruptionBudget -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ $fullName }}-apiserver"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec: {{- toYaml $kubernetes.apiServer.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels: {{- include "kubernetes.selectorLabels" $ | nindent 6 }}
      {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
    {{- end -}}
  {{- end -}}
{{- end -}}
