apiVersion: v2
name: vcluster
description: Virtual Kubernetes Cluster
type: application
version: 0.1.2
appVersion: 0.1.0
keywords:
  - vcluster
  - kubernetes
  - machine-controller
home: https://artifacthub.io/packages/helm/kvaps/kubernetes
maintainers:
  - name: "Bedag Informatik AG"
    email: sre@bedag.ch
