apiVersion: v2
name: manifests
description: "Bedag's Manifest chart. Library full of basic kubernetes manifests."
type: library
version: 0.4.7
icon: "https://www.bedag.ch/wGlobal/wGlobal/layout/images/logo.svg"
keywords:
- Bedag
- Manifests
- Library
sources:
- https://github.com/bedag/helm-charts/tree/master/charts/manifests
maintainers:
- name: SRE
  email: sre@bedag.ch
dependencies:
- name: "library"
  version: "~0.3.0"
  repository: "https://buttahtoast.github.io/helm-charts/"
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "true"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - [Fixes] Ingress port name/number validation
