##
## Global Configuration
global:
  imageRegistry: "company-registry.example.com"


## JMX Exporter
jmxExporter:
  enabled: true

## Crowd Configuration
crowd:
  cluster:
    enabled: true

  ## JVM Memory Configuration
  memory:
    min: "768m"
    max: "1536m"

  ## JVM Args (Expose JMX metrics)
  jvm_args:
    - "-Dcom.sun.management.jmxremote.port=5555"
    - "-Dcom.sun.management.jmxremote.ssl=false"
    - "-Dcom.sun.management.jmxremote.authenticate=false"
    - "-Dcom.sun.management.jmxremote.rmi.port=5555"
    - "-Djava.rmi.server.hostname=127.0.0.1"

## Proxy Configuration
proxy:
  httpProxy:
    host: "proxy.example.com"
    port: "8080"
  httpsProxy:
    host: "proxy.example.com"
    port: "8080"
  noProxy:
    - "localhost"
    - "127.0.0.1"
    - "*.example.com"
    - "{{ (index .Values.ingress.hosts 0).host }}"

## Statefulset Configuration
statefulset:

  image:
    tag: "1."
    digest: "sha256:9de1e344a34292154ca0693c13aa629c5ad1f1764fafd895ab53032dde2ad8e4"

  ## Resources
  resources:
    limits:
      cpu: 2
      memory:  3Gi
    requests:
      cpu: 0.5
      memory:  1Gi

  ## Environment Variables
  environment:

    ## Tomcat Proxy Configuration
    - name: ATL_PROXY_NAME
      value: "{{ (index .Values.ingress.hosts 0).host }}"
    - name: ATL_PROXY_PORT
      value: "443"
    - name: ATL_TOMCAT_SCHEME
      value: "https"
    - name: ATL_TOMCAT_SECURE
      value: "true"

## Persistence Configuration
home:
  storageClass: "local"
shared:
  storageClass: "nfs-backend"
  accessModes: [ "ReadWriteMany" ]
  size: "5Gi"

## Ingress Configuration
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/affinity:  cookie
    nginx.ingress.kubernetes.io/session-cookie-max-age: "10800" #3h
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: crowd.cluster.ingress
      paths: [ "/" ]
  tls:
    - hosts:
        - crowd.cluster.ingress
