{{- define "bedag-lib.values.template.job" -}}
  {{- $context := (default $ .context) }}
  {{- $_ := dict  "path" (default $context.path .path) "context" $context "data" (default dict .data) "minimal" (default false .minimal) }}
## Job activeDeadlineSeconds
# {{ $_.path }}activeDeadlineSeconds -- (int) Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer.
activeDeadlineSeconds: {{ default "" $_.data.activeDeadlineSeconds }}

## Job backoffLimit
# {{ $_.path }}backoffLimit -- (int) Specifies the number of retries before marking this job failed.
# @default -- 6
backoffLimit: {{ default "" $_.data.backoffLimit }}

## Job Completions
# {{ $_.path }}completions -- (int) Specifies the desired number of successfully finished pods the job should be run with [More Info](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/).
completions: {{ default "" $_.data.completions }}

## Job Selector
# {{ $_.path }}selector -- A label query over pods that should match the pod count. Normally, the system sets this field for you.
selector: {{ toYaml (default dict $_.data.jobSelector) | nindent 2 }}

## Job ttlSecondsAfterFinished
# {{ $_.path }}ttlSecondsAfterFinished -- ttlSecondsAfterFinished limits the lifetime of a Job that has finished execution (either Complete or Failed).
ttlSecondsAfterFinished: {{ default "" $_.data.ttlSecondsAfterFinished }}

## Job ExtraFields
# {{ $_.path }}jobFields -- Extra fields used on the Job resource
jobFields: {{ toYaml (default dict $_.data.jobExtraFields) | nindent 2 }}
#  manualSelector: true

## Pod Configuration
## {{ include "bedag-lib.utils.intern.docLink" $ }}#pod-template
  {{- if $_.minimal }}
## Supports all the values from the referenced template. Find all available values in the link above.
  {{- else }}
## Full Configuration

    {{- include "bedag-lib.values.template.pod" (set $_.data "restartPolicy" "Never") | nindent 0 }}
  {{- end }}
{{- end }}
