{{- define "bedag-lib.values.networkpolicy" -}}
  {{- $context := (default $ .context) }}
  {{- $_ := dict "parentKey" (default "networkPolicy" .key) "path" (cat (default "" (default $context.path .path)) (default "networkPolicy" .key) "." | nospace) "context" $context "data" (default dict .data) "minimal" (default false .minimal) }}
#
## - Network Policy
## Reference: https://kubernetes.io/docs/concepts/services-networking/network-policies/
##
{{ $_.parentKey }}:

  ## Enable Network Policy
  # {{ $_.path }}enabled -- Enable Network Policy Resource
  enabled: true

  ## Network Policy API version
  # {{ $_.path }}apiVersion -- Configure the api version used for the Pod resource
  apiVersion: ""

  ## Network Policy Namespace
  ## {{ $_.path }}namespace -- Define a custom namespace to deploy the Network Policy into
  namespace: ""

  ## Network Policy Labels
  # {{ $_.path }}labels -- Additional Network Policy Labels
  labels: {}

  ## Network Policy Pod Selector
  # {{ $_.path }}selector -- Pod Selector Labels for Network Policy
  selector: {}

  ## Network Ingress Policies (Slice)
  # {{ $_.path }}ingress -- Ingress Policies
  ingress: []

    ## Ingress Policy IP Block
    # {{ $_.path }}ingress[0].ipblock -- Ingress Policy IP Block
    # - ipBlock: {}
    #   cidr: 172.17.0.0/16
    #   except:
    #     - 172.17.1.0/24

    ## Ingress Policy Namespace Selector
    # {{ $_.path }}ingress[0].namespaceselector -- Ingress Policy Namespace Selector Labels
    # namespaceselector:
    #   trusted: true

    ## Ingress Policy Pod Selector
    # {{ $_.path }}ingress[0].podSelector -- Ingress Policy Pod Selector Labels
    # podSelector:
    #   app: "frontend"

    ## Ingress Policy Ports
    # {{ $_.path }}ingress[0].ports -- Ingress Policy allowd Ports
    # ports:
    #   - protocol: TCP
    #     port: 5978

  ## Network Egress Policies (Slice)
  # {{ $_.path }}egress -- Egress Policies
  egress: []

    ## Egress Policy IP Block
    # {{ $_.path }}egress[0].ipblock -- Egress Policy IP Block
    # - ipBlock:
    #    cidr: 172.17.0.0/16
    #    except:
    #      - 172.17.1.0/24

    ## Egress Policy Ports
    # {{ $_.path }}egress[0].ports -- Egress Policy allowd Ports
    # ports:
    #   - protocol: TCP
    #     port: 5978
{{- end -}}
