{{- define "bedag-lib.values.persistentvolumeclaim" -}}
  {{- $context := (default $ .context) }}
  {{- $_ := dict "parentKey" (default "pvc" .key) "path" (cat (default "" (default $context.path .path)) (default "pvc" .key) "." | nospace) "context" $context "data" (default dict .data) "minimal" (default false .minimal) }}
#
## - Persistent Volume Claim
## Reference: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
##
{{ $_.parentKey }}:

  ## Enable Persistent Volume Claim
  # {{ $_.path }}enabled -- Enable PVC Resource
  enabled: true

  ## Persistent Volume Claim API version
  # {{ $_.path }}apiVersion -- Configure the api version used for the Pod resource
  apiVersion: ""

  ## Persistent Volume Claim Namespace
  ## {{ $_.path }}namespace -- Define a custom namespace to deploy the Persistent Volume Claim into
  namespace: ""

  {{- include "bedag-lib.values.template.pvc" $_ | nindent 2 }}
{{- end -}}
