{{- define "bedag-lib.values.serviceaccount" -}}
  {{- $context := (default $ .context) }}
  {{- $_ := dict "parentKey" (default "serviceAccount" .key) "path" (cat (default "" (default $context.path .path)) (default "serviceAccount" .key) "." | nospace) "context" $context "data" (default dict .data) "minimal" (default false .minimal) }}
#
## - ServiceAccount
## Reference: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
## API Reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#serviceaccount-v1-core
##
{{ $_.parentKey }}:

  ## ServiceAccount Creation
  # {{ $_.path }}enabled -- Specifies whether a service account is enabled or not
  enabled: {{ default false $_.data.serviceAccountEnabled }}

  ## ServiceAccount Creation
  # {{ $_.path }}create -- Specifies whether a service account should be created
  create: {{ default false $_.data.serviceAccountCreate }}

  ## ServiceAccount Name
  # {{ $_.path }}name -- If not set and create is true, a name is generated using the fullname template
  name: ""

  ## ServiceAccount API version
  # {{ $_.path }}apiVersion -- Configure the api version used
  # @default -- v1
  apiVersion: ""

  ## ServiceAccount Namespace
  ## {{ $_.path }}namespace -- Define a custom namespace to deploy the ServiceAccount into
  namespace: ""

  ## ServiceAccount Labels
  # {{ $_.path }}labels -- Merges given labels with common labels
  labels: {}

  ## ServiceAccount Annotations
  # {{ $_.path }}annotations -- Annotations to add to the service account
  annotations: {}

  ## ServiceAccount Auto Mount Service Token
  # {{ $_.path }}automountServiceAccountToken -- (bool) AutomountServiceAccountToken indicates whether pods running as this service account should have an API token automatically mounted.
  automountServiceAccountToken: true

  ## ServiceAccount Image pull secrets
  # {{ $_.path }}imagePullSecrets -- ImagePullSecrets is a list of references to secrets in the same namespace to use for pulling any images in pods that reference this ServiceAccount.
  imagePullSecrets: []

  ## ServiceAccount Global PullSecrets
  # {{ $_.path }}globalPullSecrets -- Evaluate global set pullsecrets and mount, if set
  globalPullSecrets: false

  ## ServiceAccount Secrets
  # {{ $_.path }}secrets -- Secrets is the list of secrets allowed to be used by pods running using this ServiceAccount
  secrets: []
{{- end -}}
