#
# Template based on origin https://github.com/helm/charts-repo-actions-demo/blob/master/.github/workflows/lint-test.yaml
#
name: Helm Chart Linting and Testing
on: pull_request
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          config: ct.yaml
          command: lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-rc.1

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          config: ct.yaml
          command: install
