#
# Reference: https://github.com/helm/chart-testing-action
#
name: Helm Chart Linting and Testing
on: pull_request
jobs:
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Chart Linting
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Chart Installation
        uses: helm/chart-testing-action@v1.0.0
        # Only test if there are any changes
        if: steps.lint.outputs.changed == 'true'
        with:
          command: install

  documentation:
    runs-on: ubuntu-latest
    needs:
      - chart-test
    container:
      image: alpine
    steps:
      - name: Install Dependencies
        run: |
          apk add jq git curl
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Install Helm Docs
        run: |
          curl -s -L -o /usr/local/bin/helm-docs.tar.gz "https://github.com/norwoodj/helm-docs/releases/download/$(curl --silent "https://api.github.com/repos/norwoodj/helm-docs/releases/latest" | jq -r .tag_name)/helm-docs_$(curl --silent "https://api.github.com/repos/norwoodj/helm-docs/releases/latest" | jq -r .tag_name | cut -d "v" -f2-)_Linux_x86_64.tar.gz"
          cd /usr/local/bin/ && tar xfv helm-docs.tar.gz
          chmod +x ./helm-docs

      - name: Update Documentation
        run: |
          git status
          CHARTS_ROOT="./charts"
          if [ -d "${CHARTS_ROOT}" ]; then
            ## Generate Documentation
            helm-docs
            ## Push Changes
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add -A
            git commit -sam "Update Documentation" || true
            git push || true
          else
            echo -e "\n\e[33m-- Root Direcoty not found: $CHART_ROOT\e[0m" && exit 0;
          fi
